import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
    fr: {
        welcome: "Bonjour",
        republic: "République du Tchad",
        etatCivil: "ETAT CIVIL DU TCHAD",
        citizenSpace: "Espace Citoyen",
        welcomeBack: "Ravi de vous revoir.",
        welcomeBackNoDemande: "Ravi de vous revoir sur votre espace sécurisé. Toutes vos demandes sont à jour.",
        demandeInProgress: "Vous avez {count} demande en cours de traitement.",
        demandesInProgress: "Vous avez {count} demandes en cours de traitement.",
        birthCert: "Acte de Naissance",
        marriageCert: "Acte de Mariage",
        deathCert: "Déclaration de Décès",
        makeDemande: "Faire une demande",
        makeDeclaration: "Faire une déclaration",
        trackingTitle: "Suivi de Mes Demandes",
        tableType: "Type de Demande",
        tableDate: "Date de Soumission",
        tableStatus: "Statut",
        tableActions: "Actions",
        statusPending: "En cours",
        statusApproved: "Approuvée",
        statusRejected: "Rejetée",
        btnView: "Voir",
        btnDownload: "Télécharger",
        noDemande: "Aucune demande récente",
        myProfile: "Mon Profil",
        logout: "Déconnexion",
        menuDashboard: "Tableau de Bord",
        menuDemandes: "Mes Demandes",
        menuProfile: "Profil",
        menuAide: "Aide",
        // Public Home
        homeTitle: "Votre État Civil",
        homeTitle2: "À Portée de Main",
        homeSubtitle: "Effectuez vos demandes d'état civil et suivez vos dossiers, sans vous déplacer. Simple, rapide et sécurisé.",
        btnStart: "Commencer maintenant",
        btnLearnMore: "En savoir plus",
        navHome: "Accueil",
        navServices: "Services",
        navSteps: "Mes Démarches",
        navContact: "Contact",
        navConnexion: "Connexion",
        navInscription: "Inscription",
        navDashboard: "Mon Tableau de Bord",
        servicesTitle: "Nos Services Numériques",
        servicesSubtitle: "Tout ce que vous pouvez faire depuis chez vous",
        serviceBirthDesc: "Obtenez rapidement des extraits ou copies intégrales d'actes de naissance.",
        serviceMarriageDesc: "Certificats de mariage disponibles en ligne pour vos démarches administratives.",
        serviceDeathDesc: "Déclarations et demandes d'actes de décès traitées en priorité.",
        serviceTrackDesc: "Suivez l'avancement de vos demandes en temps réel via votre espace.",
        howItWorksTitle: "Comment ça marche ?",
        step1Title: "Créez votre compte",
        step1Desc: "Inscrivez-vous gratuitement en quelques clics",
        step2Title: "Connectez-vous",
        step2Desc: "Accédez à votre espace personnel",
        step3Title: "Faites votre demande",
        step3Desc: "Remplissez le formulaire en ligne",
        step4Title: "Recevez votre acte",
        step4Desc: "Téléchargez votre document validé",
        demandeSectionTitle: "Effectuer une Demande",
        demandeSectionSubtitle: "Choisissez le type de document dont vous avez besoin",
        birthCertShort: "Acte de Naissance",
        marriageCertShort: "Acte de Mariage",
        deathCertShort: "Acte de Décès",
        birthCertDesc: "Demander un extrait ou une copie",
        marriageCertDesc: "Pour les couples mariés",
        deathCertDesc: "Documents posthumes",
        // Contact Section
        contactTitle: "Contactez-nous",
        contactSubtitle: "Une question ? Besoin d'aide ? N'hésitez pas à nous contacter.",
        contactSuccess: "Votre message a été envoyé avec succès ! Nous vous répondrons dans les plus brefs délais.",
        labelName: "Nom complet *",
        labelEmail: "Email *",
        labelSubject: "Sujet *",
        labelMessage: "Votre message *",
        btnSend: "Envoyer le message",
        contactInfo: "Informations de contact",
        contactInfoDesc: "Notre équipe est à votre service pour toute question relative aux démarches administratives.",
        addrLabel: "Adresse",
        addrValue: "N'Djamena, Tchad",
        phoneLabel: "Téléphone",
        emailLabel: "Email",
        hoursLabel: "Horaires",
        hoursValue: "Lundi - Vendredi : 8h00 - 16h00\nSamedi : 8h00 - 12h00",
        // Footer
        footerAbout: "Votre administration de proximité s'engage pour une gestion moderne et transparente. Simplifiez vos démarches administratives grâce à nos services innovants.",
        footerNav: "Navigation",
        footerServices: "Services Civils",
        footerRights: "2025 État Civil Tchad - Tous droits réservés.",
        footerBuiltWith: "Développé avec ❤️ pour la République du Tchad",
        // Services Detailed
        servicesFullSubtitle: "Simplifiez vos démarches administratives avec nos solutions d'état civil en ligne, sécurisées et accessibles 24h/24.",
        serviceBirthFullDesc: "Pour toute déclaration de nouvelle naissance ou demande de copie intégrale et d'extrait.",
        serviceMarriageFullDesc: "Certifiez votre union légale et obtenez vos documents pour vos dossiers familiaux.",
        serviceDeathFullDesc: "Déclarations obligatoires et obtention d'actes pour les successions et assurances.",
        inclusiveLabel: "Inclus :",
        birthIncl1: "Déclaration initiale",
        birthIncl2: "Copie intégrale",
        birthIncl3: "Extrait avec filiation",
        marriageIncl1: "Certificat de mariage",
        marriageIncl2: "Extrait de registre",
        marriageIncl3: "Livret de famille",
        deathIncl1: "Déclaration de décès",
        deathIncl2: "Acte de décès officiel",
        deathIncl3: "Permis d'inhumer",
        whyPortalTitle: "Pourquoi passer par le portail ?",
        speedTitle: "Rapidité",
        speedDesc: "Traitement de vos dossiers en moins de 48h ouvrées.",
        securityTitle: "Sécurité",
        securityDesc: "Vos données sont protégées par chiffrement d'État.",
        zeroCfa: "0 CFA",
        freeService: "Frais de service numérique",
        // Auth Pages
        authSideTitle: "Sécurité & Identité",
        authSideDesc: "Portail officiel de gestion des actes d'état civil. Connectez-vous pour accéder à vos documents.",
        authDigital: "Numérique",
        authAvailable: "Disponible",
        loginTitle: "Connexion",
        loginSubtitle: "Accédez à votre espace sécurisé",
        labelPassword: "Mot de passe",
        forgotPassword: "Mot de passe oublié ?",
        btnLogin: "Se connecter",
        loggingIn: "Connexion...",
        noAccount: "Pas encore de compte ?",
        createAccount: "Créer un compte",
        secureGov: "Sécurisé par le Gouvernement",
        registerTitle: "Inscription",
        registerSubtitle: "Rejoignez le portail de l'état civil",
        labelFirstName: "Prénom",
        labelLastName: "Nom",
        labelEmailAuth: "Email",
        labelPasswordAuth: "Mot de passe",
        btnRegister: "S'inscrire",
        registering: "Inscription...",
        hasAccount: "Déjà un compte ?",
        forgotPassTitle: "Mot de passe oublié",
        forgotPassDesc: "Entrez votre email pour recevoir un lien de réinitialisation",
        btnSendLink: "Envoyer le lien",
        sending: "Envoi...",
        backToLogin: "Retour à la connexion",
        emailSent: "Si cet email existe, un lien a été envoyé.",
        // Admin Management
        adminDossiers: "Gestion des Dossiers",
        adminStatsAlert: "{count} demandes en attente de traitement",
        adminPaymentOk: "Tous les paiements sont à jour",
        filterAll: "Tous les dossiers",
        filterBirth: "Naissances",
        filterMarriage: "Mariages",
        filterDeath: "Décès",
        searchNNI: "Rechercher un dossier (ID, Nom...)",
        tableRef: "N° Demande",
        tableTypeActe: "Type d'Acte",
        tableSubmitDate: "Date Soumission",
        btnExamine: "Examiner",
        btnDetails: "DÉTAILS",
        btnSign: "SIGNER",
        statValidationRate: "Taux de validation",
        statProcessedMonth: "Actes traités ce mois",
        trendTitle: "Répartition des Actes",
        modalRejetTitle: "Rejeter la demande",
        modalMotifRejet: "Motif du rejet...",
        btnCancel: "Annuler",
        btnConfirmRejet: "Rejeter",
    },
    ar: {
        welcome: "مرحباً",
        republic: "جمهورية تشاد",
        etatCivil: "الحالة المدنية لتشاد",
        citizenSpace: "فضاء المواطن",
        welcomeBack: "يسعدنا رؤيتك مرة أخرى.",
        welcomeBackNoDemande: "يسعدنا رؤيتك مرة أخرى في مساحتك الآمنة. جميع طلباتك محدثة.",
        demandeInProgress: "لديك طلب واحد قيد المعالجة.",
        demandesInProgress: "لديك {count} طلبات قيد المعالجة.",
        birthCert: "شهادة ميلاد",
        marriageCert: "شهادة زواج",
        deathCert: "تصريح وفاة",
        makeDemande: "تقديم طلب",
        makeDeclaration: "تقديم تصريح",
        trackingTitle: "متابعة طلباتي",
        tableType: "نوع الطلب",
        tableDate: "تاريخ التقديم",
        tableStatus: "الحالة",
        tableActions: "الإجراءات",
        statusPending: "قيد المعالجة",
        statusApproved: "تمت الموافقة",
        statusRejected: "مرفوض",
        btnView: "عرض",
        btnDownload: "تحميل",
        noDemande: "لا توجد طلبات حديثة",
        myProfile: "ملفي الشخصي",
        logout: "تسجيل الخروج",
        menuDashboard: "لوحة القيادة",
        menuDemandes: "طلباتي",
        menuProfile: "الملف الشخصي",
        menuAide: "المساعدة",
        // Public Home
        homeTitle: "حالتك المدنية",
        homeTitle2: "في متناول يدك",
        homeSubtitle: "قم بتقديم طلبات الحالة المدنية الخاصة بك ومتابعة ملفاتك دون عناء التنقل. بسيط وسريع وآمن.",
        btnStart: "ابدأ الآن",
        btnLearnMore: "تعرف على المزيد",
        navHome: "الرئيسية",
        navServices: "الخدمات",
        navSteps: "إجراءاتي",
        navContact: "اتصل بنا",
        navConnexion: "تسجيل الدخول",
        navInscription: "إنشاء حساب",
        navDashboard: "لوحة القيادة الخاصة بي",
        servicesTitle: "خدماتنا الرقمية",
        servicesSubtitle: "كل ما يمكنك القيام به من منزلك",
        serviceBirthDesc: "احصل بسرعة على مستخرجات أو نسخ كاملة من شهادات الميلاد.",
        serviceMarriageDesc: "شهادات الزواج متاحة عبر الإنترنت لإجراءاتك الإدارية.",
        serviceDeathDesc: "يتم التعامل مع تصاريح وطلبات شهادات الوفاة كأولوية.",
        serviceTrackDesc: "تابع تقدم طلباتك في الوقت الفعلي عبر مساحتك الخاصة.",
        howItWorksTitle: "كيف يعمل؟",
        step1Title: "أنشئ حسابك",
        step1Desc: "سجل مجاناً في بضع نقرات",
        step2Title: "سجل دخولك",
        step2Desc: "الولوج إلى مساحتك الشخصية",
        step3Title: "قدم طلبك",
        step3Desc: "املأ الاستمارة عبر الإنترنت",
        step4Title: "استلم وثيقتك",
        step4Desc: "قم بتحميل وثيقتك المعتمدة",
        demandeSectionTitle: "تقديم طلب",
        demandeSectionSubtitle: "اختر نوع الوثيقة التي تحتاجها",
        birthCertShort: "شهادة ميلاد",
        marriageCertShort: "شهادة زواج",
        deathCertShort: "شهادة وفاة",
        birthCertDesc: "طلب مستخرج أو نسخة",
        marriageCertDesc: "للأزواج",
        deathCertDesc: "وثائق ما بعد الوفاة",
        // Contact Section
        contactTitle: "اتصل بنا",
        contactSubtitle: "هل لديك سؤال؟ هل تحتاج إلى مساعدة؟ لا تتردد في الاتصال بنا.",
        contactSuccess: "تم إرسال رسالتك بنجاح! سنرد عليك في أقرب وقت ممكن.",
        labelName: "الاسم الكامل *",
        labelEmail: "البريد الإلكتروني *",
        labelSubject: "الموضوع *",
        labelMessage: "رسالتك *",
        btnSend: "إرسال الرسالة",
        contactInfo: "معلومات الاتصال",
        contactInfoDesc: "فريقنا في خدمتكم لأي سؤال يتعلق بالإجراءات الإدارية.",
        addrLabel: "العنوان",
        addrValue: "إنجمينا، تشاد",
        phoneLabel: "الهاتف",
        emailLabel: "البريد الإلكتروني",
        hoursLabel: "ساعات العمل",
        hoursValue: "الإثنين - الجمعة: 8:00 - 16:00\nالسبت: 8:00 - 12:00",
        // Footer
        footerAbout: "تلتزم إدارتكم المحلية بإدارة حديثة وشفافة. بادر بتبسيط إجراءاتكم الإدارية بفضل خدماتنا المبتكرة.",
        footerNav: "الملاحة",
        footerServices: "الخدمات المدنية",
        footerRights: "2025 الحالة المدنية لتشاد - جميع الحقوق محفوظة.",
        footerBuiltWith: "تم التطوير بـ ❤️ لجمهورية تشاد",
        // Services Detailed
        servicesFullSubtitle: "بادر بتبسيط إجراءاتكم الإدارية من خلال حلولنا للحالة المدنية عبر الإنترنت، الآمنة والمتاحة على مدار الساعة.",
        serviceBirthFullDesc: "لأي تصريح بمولود جديد أو طلب نسخة كاملة ومستخرج.",
        serviceMarriageFullDesc: "قم بتوثيق اتحادك القانوني واحصل على وثائقك لملفاتك العائلية.",
        serviceDeathFullDesc: "التصريحات الإلزامية والحصول على الشهادات للمواريث والتأمينات.",
        inclusiveLabel: "يشمل :",
        birthIncl1: "التصريح الأولي",
        birthIncl2: "نسخة كاملة",
        birthIncl3: "مستخرج مع النسب",
        marriageIncl1: "شهادة الزواج",
        marriageIncl2: "مستخرج من السجل",
        marriageIncl3: "دفتر العائلة",
        deathIncl1: "تصريح الوفاة",
        deathIncl2: "شهادة وفاة رسمية",
        deathIncl3: "تصريح الدفن",
        whyPortalTitle: "لماذا نستخدم البوابة؟",
        speedTitle: "السرعة",
        speedDesc: "معالجة ملفاتك في أقل من 48 ساعة عمل.",
        securityTitle: "الأمان",
        securityDesc: "بياناتك محمية بتشفير الدولة.",
        zeroCfa: "0 فرنك",
        freeService: "رسوم الخدمة الرقمية",
        // Auth Pages
        authSideTitle: "الأمن والهوية",
        authSideDesc: "البوابة الرسمية لإدارة وثائق الحالة المدنية. سجل دخولك للوصول إلى وثائقك.",
        authDigital: "رقمي",
        authAvailable: "متاح",
        loginTitle: "تسجيل الدخول",
        loginSubtitle: "الولوج إلى مساحتك الآمنة",
        labelPassword: "كلمة المرور",
        forgotPassword: "هل نسيت كلمة المرور؟",
        btnLogin: "تسجيل الدخول",
        loggingIn: "جاري الدخول...",
        noAccount: "ليس لديك حساب؟",
        createAccount: "أنشئ حساباً",
        secureGov: "آمن بواسطة الحكومة",
        registerTitle: "إنشاء حساب",
        registerSubtitle: "انضم إلى بوابة الحالة المدنية",
        labelFirstName: "الاسم الأول",
        labelLastName: "الاسم الأخير",
        labelEmailAuth: "البريد الإلكتروني",
        labelPasswordAuth: "كلمة المرور",
        btnRegister: "إنشاء حساب",
        registering: "جاري التسجيل...",
        hasAccount: "لديك حساب بالفعل؟",
        forgotPassTitle: "نسيت كلمة المرور",
        forgotPassDesc: "أدخل بريدك الإلكتروني لتلقي رابط إعادة التعيين",
        btnSendLink: "إرسال الرابط",
        sending: "جاري الإرسال...",
        backToLogin: "العودة لتسجيل الدخول",
        emailSent: "إذا كان هذا البريد موجوداً، فقد تم إرسال الرابط.",
        // Admin Management
        adminDossiers: "إدارة الملفات",
        adminStatsAlert: "{count} طلبات في انتظار المعالجة",
        adminPaymentOk: "جميع المدفوعات محدثة",
        filterAll: "جميع الملفات",
        filterBirth: "المواليد",
        filterMarriage: "الزواج",
        filterDeath: "الوفيات",
        searchNNI: "البحث عن ملف (رقم، اسم...)",
        tableRef: "رقم الطلب",
        tableTypeActe: "نوع الوثيقة",
        tableSubmitDate: "تاريخ التقديم",
        btnExamine: "فحص",
        btnDetails: "التفاصيل",
        btnSign: "توقيع",
        statValidationRate: "معدل الموافقة",
        statProcessedMonth: "الملفات المعالجة هذا الشهر",
        trendTitle: "توزيع الوثائق",
        modalRejetTitle: "رفض الطلب",
        modalMotifRejet: "سبب الرفض...",
        btnCancel: "إلغاء",
        btnConfirmRejet: "رفض",
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(localStorage.getItem('lang') || 'fr');

    useEffect(() => {
        localStorage.setItem('lang', language);
        document.documentElement.lang = language;
        document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    }, [language]);

    const t = (key, params = {}) => {
        let text = translations[language][key] || key;
        Object.keys(params).forEach(p => {
            text = text.replace(`{${p}}`, params[p]);
        });
        return text;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
